# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

# A Travis CI configuration file.

sudo: required

language: scala

services:
  - docker

install: true

before_install:
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh

notifications:
  email: false
  webhooks:
    urls:
secure: "fHWw/KN14w+jqAbbBVkgoBlDflWJehqjRa22fKrUelaWlhNWgcTiSrYx+4ruwQj5XaSYSlKIfvRjx3qrID/gaCIVoG8LlVI0EpOsSAzgsnNj9yXYdD1PyyWoIEbeecDY9fYKKRGnevzj3L6NkmIW+51szxbgYSd+uN0tdtdWZWnadO1OUs9zKF/oyZkQxLsqGA78qYfxIN6UyKBaOsfgDLhd0NbRdJVICnHwGx7xx37wRI915pTLOlUp8o0ONpl3tiO7nYlrH0Ne8YenmhCJn8k1+zMCGkGx5P8TFWKl6sRHb2WPLyUVTdDoNjvS1NWgTgbBdcm4fK69qesyHdt8PSAezFw+ulwQyL4zMiVGD4N5wwdMfNM8F4L4jCskAHlI5gCgyGd84p4u2+Fo6YVYtG3TC9NI9vMfz2m5q9UoFOJn3AkqHejD+vXhMjnBWZGGQJVT0rk2OmSMkLhpSAZobicKnMkRT/H6O+lGpRSeDku8Sz5cXK1PDnDx1ZRsgNAj3K+iKYDXzMY17RH9uiqWyuNvO4UmgfpH1eGj441dV0RYcrNz/KREVUtRwHpCbqniatYEPlJZyIOFJzQe92jya3XvV5XRV4m5pocJlptxCQdjO5JRaV1w4HzCNKVkkALE21yjjr46kQQGt7DsSMc9KIi8J8jRL+eFnnAKyDdcdww="
